### ISSUE TITLE
Library of potentials

### ISSUE THREAD

**Issue by ahy3nz** [mosdef-hub/gmso#101]
Probably a folder of short folder of `.py` files, 

for example a `HarmonicBond.py`:
```
HarmonicBond=BondType(expression='0.5 * k * (r - r_eq)**2', 
     independent_variables={'r'})
```

Notes:
* HarmonicBond is not a subclass of `BondType`, it is merely an instance
* No parameters are specified, as this library of potentials is, so far, intended for comparing supported potentials against MD engines

**Comment by daico007** [comment]
Implemented as `gmso.lib.potential_templates.PotentialTemplateLibrary`
