### ISSUE TITLE
Pythonic considerations

### ISSUE THREAD

**Issue by ahy3nz** [mosdef-hub/gmso#104]
There may be standard libraries in Python (while considering supported versions #67 ) that we might find useful in improving performance, memory usage, or overall legibility of the code. This issue is mainly for anyone to pose some libraries that could enhance the package

* `slots` : might be useful for memory management, but foreseeably we probably won't run into memory issues
*  `typing` library : could be helpful for type checking or for a user to easily understand what goes in a function and what comes out. Could be helpful for linters or IDEs

**Comment by daico007** [comment]
type checking is now handled with pydantic
