### ISSUE TITLE
Code cleanliness standards

### ISSUE THREAD

**Issue by mattwthompson** [mosdef-hub/gmso#11]
I don't want these to be rigid requirements, but we should strive to have some basics consistently

Docstrings
* I like [numpy](https://numpydoc.readthedocs.io/en/latest/format.html) style but there are [others](https://stackoverflow.com/questions/3898572/what-is-the-standard-python-docstring-format)
* Full docstrings for classes and public functions
* One-liners for private functions

Classes
* have a `__repr__`

I will edit this according to recommendations - obviously this is just a starting point

**Comment by rsdefever** [comment]
I have a `black` check run on PRs for `mosdef_cassandra`. It doesn't edit files, just tells me if anything would be reformatted.

**Comment by daico007** [comment]
handled by pre-commit
