### ISSUE TITLE
Switch some high-level list objects to sets?

### ISSUE THREAD

**Issue by mattwthompson** [mosdef-hub/gmso#111]
Related to the case of a slow GRO file reading in #110, it looks like the offending line is `if site in self.sites:`. And it looks like `thing in list` is much slower than `thing in set`, so maybe we should convert some of our `top.sites`, `top.bonds` from lists to sites?

https://stackoverflow.com/a/40963434/4248961

**Comment by daico007** [comment]
Everything is an `IndexedSet` now.
