### ISSUE TITLE
Enumerate/Identify angles, dihedrals, etc

### ISSUE THREAD

**Issue by ahy3nz** [mosdef-hub/gmso#116]
Thinking in a workflow manner (specifically for foyer), a user will probably start with an mb.Compound -> topology.Topology. Bonds will get transferred, but the resultant Topology will not be aware of angles, dihedrals, etc.

We need a function that will search sites and bonded neighbors to find angles and dihedrals. I'll note that we can try to be fancy with connected graphs, but that would require a good assessment of different graph packages. 

This is necessary for reworking `ff.apply`. I'll tackle this issue. I will probably be basing a lot of logic off [this code that uses omm objects](https://github.com/mosdef-hub/foyer/blob/8f3019db8554fbe176981cb6a26466424c29aa1d/foyer/forcefield.py#L616)

**Comment by daico007** [comment]
solved by `identify_connection()` method
