### ISSUE TITLE
Generic untyped topology > foyer > typed topology workflow

### ISSUE THREAD

**Issue by ahy3nz** [mosdef-hub/gmso#142]
Summarizing the topology-foyer atomtyping/parametrizing discussion:

1) Have an untyped topology
2) Obtain the `top.connection_graph` (#138, #141 ). Nodes are `top.Site`, edges are `top.Bond`
2b) Create `top.Forcefield` with all the smarts definitions. Implementation still TBD, but pretty much a digitized version of the XML and some container for all that force field information
3) Atomtyping: Pass this connection_graph and forcefield to foyer to run atomtyping. Atomtyping functions largely operate on the connection_graph by tagging the nodes (`top.site` objects) with DOI and atomtype attributes (strings). Atomtyping will return the same connection_graph, just with the additional DOI and atomtype information
4) Parametrization pt 1: from this atomtyped connection graph, add `top.AtomType` to each  `top.Site` based on the atomtyped connection graph
5) Parametrization pt2: Add parameters for all bonds, angles, etc. (adding `top.BondType`, `top.AngleType`)

Other information to "parametrize" will include things like mixing rules, 14 scalings, nbfixes

Did I miss anything?

**Comment by daico007** [comment]
We have agreed on a new GMSO-centric workflow (foyer will be the backend providing typemap)
