### ISSUE TITLE
Hoomd metadata from topology

### ISSUE THREAD

**Issue by ahy3nz** [mosdef-hub/gmso#150]
Given a parametrized-topology, print out a json file that specifies force field information

* To make this generalizable, we need a pre-processing step that classifies instances of `Potential` into the engine-specific force implementations #134 
* Depending on the engine, somehow account for mixing rules or 14 interactions [this is probably for a later PR but the code will need space to account for these]
* Write out this information to the correct format-style

I'll attempt this just for writing out basic LJ information in hoomd metadata

**Comment by joaander** [comment]
HOOMD v3 will use pickle files for this. Work is almost complete on the PR: https://github.com/glotzerlab/hoomd-blue/pull/944
