### ISSUE TITLE
Define proper hashing and equality checks and containment logic

### ISSUE THREAD

**Issue by umesh-timalsina** [mosdef-hub/gmso#175]
#90, #164, #112, #122, #14 , #17 All of these issues should be a good starting point for all the quandaries and quibbles we had around equivalence of various objects and classes we have. This issue is dedicated to a discussion which leads to a proper implementation of core equivalence and equality checks, which should serve robustly, consume less memory and time (Fair tradeoff) and do not violate fundamental principles around `hashability` and `mutability`. Should be a fair game implementation of various object method overrides `__hash__`, `__eq__` and `__clone__`, with some extra pointer objects. Discussions and comments to follow as implementation progresses.

**Comment by daico007** [comment]
Should now be handled via pydantic serialization
