### ISSUE TITLE
Create OpenMM XML Converter

### ISSUE THREAD

**Issue by umesh-timalsina** [mosdef-hub/gmso#195]
In ForceField Class, when specifying an XML file to the constructor there should be a way to handle intermediate XML representations like the one from OpenMM, so that it would be less of a hassle to users of this package to know/ care about how we use XML files. 

For this we need to create a converter, generic enough to handle different XML files. The idea was teased in https://github.com/mattwthompson/topology/issues/191#issuecomment-576734105.

From https://github.com/mattwthompson/topology/pull/186#issuecomment-563323125, @mattwthompson Commented: 

Mapping of OpenMM objects to our objects:

| OpenMM  | topology |
|-|-|
|  AtomTypes  | AtomTypes | 
|  Residues | None |
|  HarmonicBondForce | BondTypes |
|  HarmonicAngleForce | AngleTypes |
|  PeriodicTorsionForce | DihedralForces |
|  RBTorsionForce | DihedralForces |
|  CMAPTorsionForce | None |
|  NonbondedForce | Wrapped into AtomTypes |
| GBSAOBCForce | None |
| CustomBondForce | Not necessary |
| CustomAngleForce | Not necessary |
| CustomTorsionForce | Not necessary |
| CustomNonbondedForce | Not necessary |
| CustomGBForce | Not necessary |
| CustomManyParticleForce | Not necessary |

**Comment by daico007** [comment]
done by `forcefield-utilities`
