### ISSUE TITLE
More (small) XML files for testing

### ISSUE THREAD

**Issue by mattwthompson** [mosdef-hub/gmso#211]
Right now we don't have enough files in our XML testing (`topology/tests/files` needs to have 10-20 files)

* Water models - Ray
* Simple molecules (i.e. methane or H2S) with force fields like OPLS, GAFF - Justin, Co
* Simple bonded structures (i.e. for graphene/buckyball) - Matt
* A CG/UA structure (like TraPPE-UA)? - Parashara

We can start with Foyer XML files, convert them over to this format. For tests, we want to be able to load them in and check some or all values to make sure they're read in properly.

**Comment by daico007** [comment]
several XMLs have been added
