### ISSUE TITLE
Example running MD simulation in HOOMD

### ISSUE THREAD

**Issue by mattwthompson** [mosdef-hub/gmso#215]
Can build off the Argon example I showed last week?

@vyasr Could you or Josh take a stab at this? Alex has done much of the work, I think, in #151. This doesn't need to be complex or rigorous now, I just want to be able to run a simple MD simulation without loading in parmed, mdtraj, etc.

**Comment by vyasr** [comment]
I somehow completely missed being tagged on this issue, sorry about that. I think given the current development directions (and Josh's last comment) it makes sense to hold off on this until HOOMD v3 is in beta, but let me know if there was a different decision made at any point and I can take a stab at writing an example.

**Comment by joaander** [comment]
The current state of `feature/new-object-API` is capable of LJ interactions, bonds, angles, dihedrals, impropers, and a Langevin thermostat which I demonstrated at the all hands meeting using mbuild per @mattwthompson 's request. We could certainly get a prototype example of LJ simulations with GMSO working now and update it if the v3 API undergoes changes later.

**Comment by daico007** [comment]
Now included in `test_hoomd.py`
