### ISSUE TITLE
Defining equivalency between `subtops`

### ISSUE THREAD

**Issue by rmatsum836** [mosdef-hub/gmso#248]
Began discussion of this in #236, but in order to elegantly write out atoms and molecules to GROMACS top files, I think it will be necessary to get a unique set of `subtops` from a `topology` object.  This will require a method that compares `subtops`.

One option we discussed was to compare the `atom_types` within a `subtop`, since these data structures can be equivalent.  Another option is going a step further, and writing out a graph class that can more explicitly compare the bonds, angles, and dihedrals within `subtops`.

**Comment by daico007** [comment]
Subtop will be removed in next release
