### ISSUE TITLE
Unit scale

### ISSUE THREAD

**Issue by mattwthompson** [mosdef-hub/gmso#262]
Posting there here in case it becomes a common pain point. In our research, we often use extrinsic and intrinsic (kcal vs. kcal/mol) and macroscopic vs micoscopic/molecular (Coulomb vs elementary charge) units interchangeably, which can be a problem for a computer (i.e. `unyt`) that parses things in a strict manner.

https://github.com/mattwthompson/topology/issues/257 https://github.com/mattwthompson/topology/pull/244

**Comment by umesh-timalsina** [comment]
Closing this in favor of #315.
