### ISSUE TITLE
Atomtype naming vs Sitetype

### ISSUE THREAD

**Issue by justinGilmer** [mosdef-hub/gmso#308]
Currently we define our "Site" types as AtomTypes, while they should probably be named `SiteType`

From the alllhands meeting @ vanderbilt

**Comment by mattwthompson** [comment]
Do we want a discrete `SiteType` class that covers most of what `AtomType` currently does, and a new `AtomType` class that basically inherits from `SiteType` and enforces that an element exists?


`Potential`: Most sympy/unyt processing
`SiteType`: General container for most non-bonded stuff, inherits from `Potential`, can apply to any sort of interacting particle
`AtomType: Inherits from `SiteType` but must have an element attribute

**Comment by daico007** [comment]
I think we are sticking with AtomType nomenclature for the foreseeable future
