### ISSUE TITLE
 handling addition of topologies

### ISSUE THREAD

**Issue by rmatsum836** [mosdef-hub/gmso#32]
I just tried adding water and ion parmed structures together and writing out to a PDB file for use with OpenMM. It seems that when I did so, the water molecules were written out to the pdb as a single molecule. As a result, OpenMM wasn’t able to map any of these waters to their respective atom types.

There might be a way to handle this through Parmed, but I wanted to just document this as we might be able to handle this in a better way when we add two topologies together.

**Comment by daico007** [comment]
Duplicated
