### ISSUE TITLE
Improvements to LAMMPS writer

### ISSUE THREAD

**Issue by mattwthompson** [mosdef-hub/gmso#320]
Please post MWE of systems you currently write to LAMMPS so we can piece out the features we need to add

**Comment by mattwthompson** [comment]
@zijiewu3 @jingxiangguo @shivrajkotkar @rsdefever @rwsmith7531 ?

**Comment by rmatsum836** [comment]
There have been incremental improvements to the LAMMPS writer in mBuild that need to be implemented in GSMO as well.

**Comment by zijiewu3** [comment]
In general, blank lines are important in LAMMPS data files for them to be parsed properly
```
LAMMPS data file for CLP  #a brief title line describing the data file
           #A blank line is needed
1800 atoms #total number of atoms in the simulation box
1770 bonds 
1740 angles 
690 dihedrals 
0 impropers 

5 atom types #total number of atom types in the simulation box
2 bond types 
2 angle types 
2 dihedral types 
0 improper types 

-55.000000 55.000000 xlo xhi   #dimension of the box
-55.000000 55.000000 ylo yhi 
-55.000000 55.000000 zlo zhi 

Masses  #Mass of each atom type
              # blank line is important 
1 3.000000
2 3.000000
3 3.000000
4 1.000000
5 1.000000
               #This is a blank line that is needed.
#This is NOT a blank line but a comment. In general, bonded/nonbonded potential coefficients can be specified either here or in input script. (but not the styles; styles have to be in input script). In our workflow, we tend to keep the coefficients in the input script instead of specifying them here.
Atoms #list coordinats of all the atoms, ID molecule type charge x y z nx ny nz
           #blank line is important
1 1 2 0.000000 -34.029404 26.234295 5.080472 0 0 0
2 1 3 0.000000 -34.029404 26.234295 5.580472 0 0 0
...
1800 30 4 0.000000 50.340269 -54.531059 22.185637 0 0 0

Bonds #list all bonds, ID type atomID_1 atomID_2

1 1 1 2 
2 1 2 3 
...
1770 1 1793 1796 

Angles #list all angles. ID type atomID_1 atomID_2 atomID_3

1 1 1 2 3 
2 2 4 1 2 
...
1740 1 1793 1796 1797 

Dihedrals  #list all dihedrals. ID type atomID_1 atomID_2 atomID_3 atomID_4

1 1 4 1 3 5 
2 1 9 6 8 10 
...
690 2 1795 1793 1796 1799

**Comment by shivrajkotkar** [comment]
I have posted my workflow here. Let me know if you need any clarification.
Thanks.
[https://github.com/shivrajkotkar/lammps_workflow](url)

**Comment by rmatsum836** [comment]
Working on implementing bonds and angles into the writer.  PR to come soon.

**Comment by rmatsum836** [comment]
#339 recently got merged and hoping #331 is to follow soon.  Also adding a reader in #351, with which we can start validating the data files being written out.  Here is a short list of things to accomplish:

- Add support for additional unit styles (LJ, metal, etc.)
- Add support for additional potentials (Mie, fene, etc.)
- Add support for additional atom styles (anything other than 'full')
- Handling of impropers

**Comment by rmatsum836** [comment]
#461

**Comment by daico007** [comment]
Should have mostly addressed by https://github.com/mosdef-hub/gmso/pull/701
