### ISSUE TITLE
How to create Potential Templates? User Guide as well as discussion

### ISSUE THREAD

**Issue by justinGilmer** [mosdef-hub/gmso#333]
We dont have much documentation for contributing potentials to gmso. This should be updated. 

Other contributions should probably be highlighted too.

**Comment by umesh-timalsina** [comment]
The potential templates should be saved as JSON files in lib, with distinct keys and values.  On importing the lib you should be able to make objects on the fly.

**Comment by umesh-timalsina** [comment]
PotentialTemplate Classes Should be immutable
