### ISSUE TITLE
Do we want bond.bond_type to be an alias for bond.connection_type?

### ISSUE THREAD

**Issue by uppittu11** [mosdef-hub/gmso#335]
It doesn't look like `Bond` doesn't have a `bondtype` attribute. It only has `connection_type`. 
```suggestion
            bond.connection_type = ff.bond_types["opls_111~opls_112"]
```

https://github.com/mosdef-hub/gmso/blob/aa1d2a43719dae6e1c1a21ec5c9e2b4a1a44ffbf/gmso/core/bond.py#L33

_Originally posted by @uppittu11 in https://github.com/mosdef-hub/gmso/pull/330/review_comment/create_

**Comment by mattwthompson** [comment]
My vote is for a `bond.bond_type` attribute to exist, but only as an alias for `bond.connection_type` unless we want to move some of that code over

**Comment by rmatsum836** [comment]
I think an alias is the way to go as well.

**Comment by rsdefever** [comment]
What is the benefit of having the `bond.bond_type` attribute vs. `bond.connection_type`? I'm not necessarily opposed but more attributes seems more complex. Especially if it is just an alias for something that already exists.

**Comment by mattwthompson** [comment]
It just seems more natural to me that bonds should have bond types. I forget how we ended up with `connection_type` as the main attribute, if it was something we intended to be the final implementation or something that was just for staging the feature

**Comment by rsdefever** [comment]
Agree that there is logic to the `bond` and `bond_type` reasoning. A benefit of using `connection_type` is that it is generalizes. I don't have to wonder what the attribute name is going to be.  But, to counter my own point, if we use a sensible and consistent naming scheme `bond` <--> `bond_type`, `angle` <---> `angle_type`, etc., then perhaps any possible benefit of just using `connection_type` is nullified.

**Comment by mattwthompson** [comment]
Yeah, I'm not sure if aliasing or renaming is the better choice here

**Comment by daico007** [comment]
`connection_type` is now alias for `bond_type`
