### ISSUE TITLE
Drop Boltons

### ISSUE THREAD

**Issue by umesh-timalsina** [mosdef-hub/gmso#336]
I think we can drop `boltons` from the requirements with some minor changes.

**Comment by mattwthompson** [comment]
What changes? We still use it https://github.com/mosdef-hub/gmso/search?q=indexedset&unscoped_q=indexedset

**Comment by umesh-timalsina** [comment]
But this could be a set now. Its not mandatory to use an IndexedSet.

**Comment by mattwthompson** [comment]
I think after #343 we are reliant on `IndexedSet` over the built-in `set`

**Comment by rmatsum836** [comment]
We could reformat our writers to not be reliant on `IndexedSet`, but I'm not sure if it's worth it  just to remove boltons as a dependency.  The `IndexedSet` makes it much easier to write out all of the system information.

**Comment by justinGilmer** [comment]
I guess if we really wanted it and did not want to use the full boltons, we could use its source code as long as we attribute it properly. Its a custom license, but is very similar to MIT.

https://github.com/mahmoud/boltons/blob/master/LICENSE
