### ISSUE TITLE
Migrate to Python 3.6 `fstrings`

### ISSUE THREAD

**Issue by justinGilmer** [mosdef-hub/gmso#344]
At the all hands, we decided on supporting newer versions of Python only (I think 3.6+, but it might be 3.7+ @mattwthompson , do you recall?)

For formatting our writers, and other string formats, `fstrings` seem like a major feature we should leverage.

**Comment by rmatsum836** [comment]
I agree, I believe f-strings were introduced in 3.6 so it should be safe now to implement them.

**Comment by mattwthompson** [comment]
I'm iffy on 3.7+ but I am fine agreeing to 3.6+ moving forward

**Comment by bdice** [comment]
The easiest way I know to migrate to f-strings is to use pyupgrade.

https://github.com/asottile/pyupgrade

`$ pyupgrade --py36-plus`

**Comment by vyasr** [comment]
[Yup 3.6 for f-strings](https://docs.python.org/3/reference/lexical_analysis.html#formatted-string-literals). On the topic of choosing Python versions, for what it's worth many tools in the SciPy ecosystem (and many Glotzer lab tools as well) are now (explicitly or implicitly) tracking [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html). In case that wasn't discussed at the all hands meeting, that may be something you may want to adopt as well in the future.
