### ISSUE TITLE
Clear definition of dihedrals vs propers vs impropers

### ISSUE THREAD

**Issue by mattwthompson** [mosdef-hub/gmso#346]
See [this](https://github.com/mosdef-hub/gmso/pull/338#discussion_r389802779) thread

It's non-negiotable to me that there should be a clear distinction between proper and improper dihedrals. But it's not so clear to me if "dihedrals" should refer strictly to propers (and not impropers) or if we want it to be an umbrella term encapsulating both propers and impropers. My preference is for the umbrella idea, but any solution is fine to me as long as we are consistent across this project.

Ryan and I are curious what others think (and this is something we need many people's input on!)

**Comment by daico007** [comment]
I prefer the umbrella treatment for dihedral

**Comment by rmatsum836** [comment]
I think having an umbrella term is fine if we're also including topology attributes separately for propers and impropers.

**Comment by justinGilmer** [comment]
It makes sense to me, that we still have a dihedral class, that `proper` and `improper` inherit from. although that might make things a bit more confusing?

**Comment by mattwthompson** [comment]
It seems like the umbrella proposal is popular. Once we get a few of these PRs merged I will make a new PR implementing this idea.

**Comment by daico007** [comment]
I think we have been going with Proper vs Improper as 2 separate classes for a bit now, and I don't think we are planning to overhaul that in the foreseeable future
