### ISSUE TITLE
Replace `allclose` function with `unyt.array.allclose_unit`

### ISSUE THREAD

**Issue by rmatsum836** [mosdef-hub/gmso#348]
We have our own function in `utils/testing.py` called `allclose` that compares to unyt arrays.  However, the unyt package has its own function that handles this comparison called `unyt.array.allclose_units`.  

I am proposing to remove this function from our package and use the Unyt function instead.  On a somewhat unrelated note, we also have some assert statements in our testing such as:
```
assert np.allclose(unyt1.value, unyt2.value)
```
We should update these tests so that the entire unyt array is compared.

**Comment by justinGilmer** [comment]
Oh that is nice. I remember that was our original intention for our own util. But now that Unyt handles it itself, I am absolutely down with this idea.

There is also an assert version of the same check:
https://unyt.readthedocs.io/en/stable/modules/unyt.testing.html#unyt.testing.assert_allclose_units

**Comment by mattwthompson** [comment]
I am tagging this as a good first issue, since I think it would be instructive for a @mosdef-hub/mosdef-contributors to go through the tests and update calls to this function

https://github.com/mosdef-hub/gmso/search?q=allclose&unscoped_q=allclose

**Comment by Argon1999** [comment]
This issue has been completed refer to Pull Request #413 on mosdef-hub/gmso. Please review and merge if it's good.

**Comment by daico007** [comment]
Closed by #413
