### ISSUE TITLE
@unyt.accepts/returns decorators for validating function inputs and ouputs

### ISSUE THREAD

**Issue by mattwthompson** [mosdef-hub/gmso#349]
This seems like a nifty feature; functions can be decorated to explicitly take in and returns units of particular dimensions: https://unyt.readthedocs.io/en/stable/usage.html#checking-units

P.S. I'm still not sure I can explain what a decorator is without context

**Comment by daico007** [comment]
is this handled by `pydantic` @umesh-timalsina?

**Comment by umesh-timalsina** [comment]
Not particular dimensions but we have a util function called `ensure_valid_dimesnions` added in #431.

**Comment by daico007** [comment]
I think this issue is covered then.
