### ISSUE TITLE
Add ethane test case

### ISSUE THREAD

**Issue by rmatsum836** [mosdef-hub/gmso#352]
Since our writers are starting to have the capability to write our dihedrals, we should add an ethane pytest fixture to test that dihedrals are written our correctly.

**Comment by mattwthompson** [comment]
+1, I like the idea of slowly building out these fixtures. pytest makes it easy to iterate over them and build a (fixtures) x (writer/converter) sort of matrix

**Comment by daico007** [comment]
Added per #383
