### ISSUE TITLE
Remove and Replace `topology_site` fixture

### ISSUE THREAD

**Issue by rmatsum836** [mosdef-hub/gmso#354]
Since we've recently added pytest fixtures for untyped and typed Ar and water systems, I think we can remove the `topology_site` fixture and replace it.  

I believe this fixture is currently only being used in the lammps and openmm tests.

**Comment by mattwthompson** [comment]
+1, the Argon fixture could probably be dropped down from 100 atoms, or maybe modified to take in N in order to accomadate systems of different sizes, if we need just a single-site system

**Comment by daico007** [comment]
I agree, modifying the Ar to take in N as an argument seems like the better option

**Comment by rmatsum836** [comment]
I agree, this would be useful for the unit tests @rsdefever wrote for his MCF writer #340.
