### ISSUE TITLE
Parmed conversion improvement

### ISSUE THREAD

**Issue by daico007** [mosdef-hub/gmso#357]
There are still a few things that still need to be implemented to the Parmed conversion functions in the future:
- Add improper dihedrals conversion (#338, might need to wait for #355)
- Better handling of partially typed structure

**Comment by daico007** [comment]
A few things (to do) to add to this issues:
- I forgot to add the msg to the assertion check (`convert_parmed.py` line 352) .
- Bug found on `to_parmed` method: 
```
> from mbuild.lib.molecules import Ethane
> from gmso.external import from_mbuild, to_parmed
> ethane = Ethane()
> top = from_mbuild(ethane)
< A bunch of warnings pop up> 
> struc = to_parmed(top) 
>   File "/Users/daico007/Documents/dev/env/gmso/gmso/external/convert_parmed.py", line 379, in to_parmed
    residue_idx = int(residue[residue.find('[')+1:residue.find(']')])
ValueError: invalid literal for int() with base 10: 'CH'
```
I believe this bug is because of one assumption I made about the subtop naming convention when doing the hierarchy translation (line 370-372), which is only true if the topology come directly from `from_gmso`.  Will try to fix this soon.

**Comment by mattwthompson** [comment]
@daico007 could you do me (and the world) a favor and document things thoroughly when you get to working on ParmEd's handling of impropers? Not just user-facing docs, but developer-facing docs/notes. It's been a thorn in our side for a long time

**Comment by daico007** [comment]
I will definitely do that
