### ISSUE TITLE
Handling 1-4 scaling factors in Topology objects

### ISSUE THREAD

**Issue by rsdefever** [mosdef-hub/gmso#363]
This discussion started from #340. 

The question is how we should store 1-4 scaling factors in a `Topology`. For example, when writing an MCF file I need to know what the 1-4 scaling factors are. 

I'll start this thread by pasting the discussion so far.

Matt: 

> At different points in time we've passed around the idea of having a top.force_field attribute that just points to a ForceField object. It doesn't seem like this is implemented, and much of the important data is stored by parsing through the type objects directly, not by passing through a force field class. The two ideas I can come up with are

> 1. Add a top.force_field attribute that behaves as a pointer, so we could do things like top.force_field.scaling_factors['whatever']. This assumes, for now, that there is only one force field per topology, and also that the data contained in each should match.

> 2. Add the scaling factors to the Topology class directly, so that they can be accessed through top.scaling_factors['whatever']. This might be tricky to bookkeep without clear relationships between the classes, but can be done if we are careful

Justin: 

> Hmm that is a good point. Ive been thinking this over and I think I am a bit more on board with number 1. However, it is sort of the opposite of how we do things now. The sites and such have the atom types, once it is a typed topology. I feel like either the atomtypes should carry this, which is a bit redundant or it is carried at the top of the topology's hierarchy.

> Although I am not married to either idea yet. But this will be an issue we need to solve soon, since this information we will need when writing out typed systems to most engines.

> Maybe we do just carry a pointer to the forcefield, and if the system is typed, we should be able to use the scaling factor from that forcefield.

> Although this leads to another issue if you wanted to write out a topology object to a serializable format. Since the forcefield will not be following along (unless we decide to do that either by writing out the xml again, or including all the xml data in the json as well, or when loading in from a JSON file, we could specify if we want to bring the FF information contained in the json, or load a new ff with the structure.), if we are relying on the FF object for that information, we lose that.

Let's get some other opinions here!

**Comment by mattwthompson** [comment]
I think, as a stop-gap, having high-level dicts that carry this sort of metadata in the topology, force field, or both objects is fine. Option 2 of what I presented before would be the easiest patch to get things working now.

I think the real issue here is defining the relationship between a topology and a force field. We have had some discussions about this in the past, but haven't really implemented them in the actual code. This would involve making some decisions about what goes where and what is and isn't allowed to be manipulated. In other words, properly doing Option 1.

**Comment by rsdefever** [comment]
Ok its a year later and we need to do something. 

I'm opening up a PR that adds scaling factors to the topology object. 

_Most of the time_ scaling factors are defined _system wide_. Based upon that, I think it makes sense for a `Topology` to carry scaling factors with it.

**Comment by ahy3nz** [comment]
I agree, most of the time scaling factors are defined system-wide, but then there are the situations where they're not (apparently in glycam). 

https://github.com/ParmEd/ParmEd/issues/1136

https://github.com/openforcefield/openff-system/issues/106

https://twitter.com/aaryakat/status/1363108109472858112

**Comment by rsdefever** [comment]
One option would be to carry any non-default scaling factors with the connections. In this way we could support custom 1-2, 1-3, and 1-4 factors.

**Comment by justinGilmer** [comment]
> One option would be to carry any non-default scaling factors with the connections. In this way we could support custom 1-2, 1-3, and 1-4 factors.

I am definitely in favor of something like this. If a connection has a defined scaling factor, then we use that, otherwise we use the system default. It would have consistent behavior to our charge attribute for particles (use elemental charge unless the particle itself has a defined charge).

**Comment by mattwthompson** [comment]
You may wish to throw in 1-5 scaling factors into the mix while you're at it, with whatever solution you use for 1-2, 1-3, and 1-4.
