### ISSUE TITLE
Necessity of connections in topology. Should we remove them?

### ISSUE THREAD

**Issue by umesh-timalsina** [mosdef-hub/gmso#373]
The `topology.connections` indexed set is currently carrying redundant information. We had a discussion around this but we never formalized what needs to be done with them. I am pinning this one here.

**Comment by uppittu11** [comment]
These are just pointers to the various bonds, angles, and dihedral objects, so that indexed set would still be very lightweight, right? Is it doubling the memory usage?

**Comment by umesh-timalsina** [comment]
No its not. But with the kind of bookkeeping we have, It would be an extra object to maintain (while removing sites for example). I am not totally against it but if not used, we could remove it.

**Comment by mattwthompson** [comment]
A `gmso.Topology` absolutely needs to know about the bonds, angles, torsions, etc. contained within it. I suppose `topology.connections` serves less of a purpose, but I kinda like having it there. Were there any other diagnostics done on this issue?

**Comment by uppittu11** [comment]
what if we remove the `topology._connections` attribute and make `topology.connections()` return the concatenation of `topology.bonds`, `topology.angles`, `topology.dihedrals`, and `topology.impropers`. That you won't have redundant information and there would be less bookkeeping.

**Comment by umesh-timalsina** [comment]
Topology `connections`  and `connection_types` should be a `ChainMap`, this is the best datastructure that makes sense. https://docs.python.org/3/library/collections.html#collections.ChainMap
