### ISSUE TITLE
Site Properties

### ISSUE THREAD

**Issue by umesh-timalsina** [mosdef-hub/gmso#385]
1. Currently, a site in GMSO can access its connection, should we remove it?
2. `n_connections` property in a site. Is it worth it?
3. Should an atom_type be associated with a site? Or, should that information be stored in a Topology only?

**Comment by uppittu11** [comment]
Here is my opinion on this:
1. The hierarchy of physical GMSO objects is 
`Topology` (highest) -> `Subtopology` -> `Connection` -> `Site` (lowest). 
And each object shouldn't be able to access the objects above it in the hierarchy. So, a `Site` shouldn't be able to access `Connection`s.  
2. `n_connections` isn't necessary to store in site. The only time we might need it is if the atom type assigned to a site depends on its hybridization state (sp2, sp3, etc.). And even so, this would only matter if the site is in a topology. So, it might be worth having a dictionary mapping `{site: connections}` within topology, but the number of connections doesn't need to be a site property. 
3. This one is a little more controversial, but I think that a sites should not be able to access their `atom_type`. The assignment of atom types to a site is only relevant when the sites and atom_types are inside of a topology, so the `{site: atom_type}` mapping should be done only in topology.

**Comment by rmatsum836** [comment]
1.  I agree with @uppitu11.  This would remove a lot of the bookkeeping, and would allow us to get rid of the update functions which have been a big bottleneck.
2. I'm a little bit more on the fence here.  I think I would be okay with this if we did have a dictionary that mapped sites to connections within topology, that way that information is still easy for a user to access if wanted.  A little more off-topic, but I'm not sure `n_connections` being a sum of all bonds, angles, and dihedrals is super useful.
3. I think I'm actually okay with this, as long as we have the `{site: atom_type}` dictionary mapping within topology.  But I think I would at least want to have an attribute `is_typed` or something like that to distinguish between sites that have types and sites that don't.  I'm also unsure about the scenario where a user may want to take a subset of atoms that have `atom_type I` and tweak a parameter.  In this case, should we direct them to initialize a new `atom_type J` that would be point to those specified atoms?

**Comment by daico007** [comment]
1. I am agree with both @uppittu11 and @rmatsum836 on this matter.
2. Having a dictionary mapping sounds good to me.
3. I think site should know it type, but I think it should be static/readonly. As in user should not be able to modify an atom_type by `site.atom_type['sigma'] = <something random>`. Instead, I think we should have another layer, like object method, may be `set_atom_type(self, type)`, and `modify_atom_type(self, parameters, apply_to_all = False)`, where the `apply_to_all` flag would indicate whether we want to all the parameters of that type, or we want to only change to apply to this specific site. At the top level, I think the topology should have knowledge of these types information too (may be where the observer can come in?).

**Comment by justinGilmer** [comment]
1. I am also in agreement with @uppittu11 's hierarchy, as well as accessing rules.
1. I am still on the fence with this one. Maybe this would just be a top-level method, pass in the site of interest, and find all the matches in connections. I could just as well see this as an attribute of the site. That object is in charge of its state, and connections do affect its state.
    * I also agree that n_connections is not too useful. However, we should definitely know the `n_bonds`, `n_angles`, `n_dihedrals`, `n_propers`. And `n_connections` could still exist.
1. @uppittu11 , that seems quite reasonable. An atom-type is not an inherent property of a site, especially when not in a topology. I also really like @daico007 's suggestion here. I think as long as we keep a map somewhere, that is fine. I think the `apply_to_all` parameter would be an excellent feature. However, I am unsure how we want to implement that. Maybe the only way to edit an attribute of an atom_type, bond_type, etc. would have to be through topology methods? I am having a hard time trying to figure out how we could accomplish that though.

**Comment by mattwthompson** [comment]
1. I agree with 3/4 of those relationships; I do not view `Connection`s as "umbrellas" to `Sites` in any analogous manner to `Topology` -> `Subtopology` -> ... `Site`. It may be a distinction without a difference, but I see it as being either on the same level in the hierarchy a `Sites` or not in them at all. I view the scope as simply definition relationships between sites - or at least that should be the intent; implementation may be more difficult.
1. I do not have a strong opinion on the question as stated, but it is integral that a user or API be able to determine how many neighbors a given `Site` has. The dictionary-based mapping at the high level seems to be able to accomplish this, and if it makes implementation easier then it seems good.
1. I echo others' opinions above; similar to 2., there is a feature that needs to be supported and the best way to implement it should be picked. Making a `Site.atom_type` attribute as a pointer was just what felt sensible at the time; a dictionary mapping should be pursued if that makes the implementation of this feature more tractable.
