### ISSUE TITLE
TOP writer is incorrectly indexing atoms

### ISSUE THREAD

**Issue by uppittu11** [mosdef-hub/gmso#388]
The top file format starts their indexing from 1 instead of 0 so the index of the atoms for the bonded parameters is off by one. 

e.g. 
https://github.com/mosdef-hub/gmso/blob/master/gmso/formats/top.py#L140-L141

The syntax for getting site indices should also change with #367 being merged.

**Comment by daico007** [comment]
I believed this has been fixed
