### ISSUE TITLE
Bookkeeping Topology Objects with a consolidated class

### ISSUE THREAD

**Issue by umesh-timalsina** [mosdef-hub/gmso#396]
As added by #367, #375 etc... among others, there will be plenty of booking objects required for a topology. They follow a similar pattern:
1. They need to be indexed.
2. They need to track changes on their constituents.

Once all these PRs get merged, It might be nicer to consolidate all these objects into a single Container. For example -> A `TrackedContainer` with three properties (1.) Index (2.) Objects (3.) associations (Non exaustive list within the realms of current PRs). This would decrease the amount of bookeeping done in Topology by delegating bookkeeping responsibility  to the `TrackedContainer` class itself.

**Comment by daico007** [comment]
These indexes are now generated on the flight.
