### ISSUE TITLE
Why are we running pytest twice?

### ISSUE THREAD

**Issue by uppittu11** [mosdef-hub/gmso#397]
https://github.com/mosdef-hub/gmso/blob/ec541a47ce87138b67770e521c654088ed35a9fb/azure-pipelines.yml#L70-L71

#316 is the culprit? We could probably delete the first pytest. 

On a related note, AZP has better integration with codecov now, so we can use the bash uploader instead: https://docs.codecov.io/docs/about-the-codecov-bash-uploader. This way the token won't be accessible to the public (although I guess it won't be too hard to look through the git history).

**Comment by vyasr** [comment]
For security purposes, you can [store the token as an environment variable with optional encryption through the AZP UI](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#user-defined-variables) and then use that variable instead in your yml file. Probably not a big deal for codecov, but might be useful if you ever start automating deployment to PyPI or something like that.

**Comment by uppittu11** [comment]
Also this needs to be fixed:
https://github.com/mosdef-hub/gmso/blob/ec541a47ce87138b67770e521c654088ed35a9fb/codecov.yml#L1-L3
`mbuild` -> `gmso`

**Comment by mattwthompson** [comment]
lol if you go into the blame you'll see this excellent commit is the culprit https://github.com/mosdef-hub/gmso/commit/351989264d448edbdb9e6e96dfc8055316fc2723
