### ISSUE TITLE
Pass in list/dictionary of elements for from_mbuild

### ISSUE THREAD

**Issue by uppittu11** [mosdef-hub/gmso#399]
It's pretty cool that you use a function to extract the `Element` from `Site.name`. To make it even more flexible we could also add an argument to `from_mbuild` which takes in a dictionary of mbuild `Particles` (`Compounds`) and maps them to an element, so that you can name your Sites whatever you want. We could also make the `element` module more accessible to the user so that they can easily make custom functions to pass in to the `search_method` argument. 

Ultimately, the `Site.element` is what foyer will use to atom type, so it would be good to make it easy to assign elements. 

https://github.com/mosdef-hub/gmso/blob/ec541a47ce87138b67770e521c654088ed35a9fb/gmso/external/convert_mbuild.py#L52-L59

**Comment by daico007** [comment]
This method now extract the info from `particle.element`
