### ISSUE TITLE
Method to take box vectors as input and generate a Box class

### ISSUE THREAD

**Issue by justinGilmer** [mosdef-hub/gmso#40]
To keep the `Box` class simple, we support only taking in [a,b,c][alpha, beta, gamma] as inputs.

#1 we agreed that it would make the most sense to just define methods as we needed them to read in other box definition formats. From #26 we need the support of reading in `GRO` file box formats and converting them to the inputs for our `Box`

**Comment by daico007** [comment]
functionality added
