### ISSUE TITLE
Fix channel priority in azure pipelines

### ISSUE THREAD

**Issue by umesh-timalsina** [mosdef-hub/gmso#418]
In AZP, the channel priority is set in such a way that `mbuild` is always grabbed from `mosdef` channel. Since, the recent releases of `mbuild` have been in `conda-forge` channel, we find a way to fix channel priorities in `azure-pipelines`.

**Comment by mikemhenry** [comment]
Do we still release new versions of `mbuild` on the `mosdef` channel? If we don't, then a quick fix would be to specify the minimum version number/first version that was on `conda-forge`.

**Comment by umesh-timalsina** [comment]
No we don't use `mosdef` channel for mbuild but I get the point. We should may be pin mbuild version (`mbuild >= 0.10.5`) as well.

**Comment by daico007** [comment]
I think 0.10.5 is the last version of mbuild released on the mosdef channel, so probably we need to pin it to >= 0.10.6  or something

**Comment by mattwthompson** [comment]
Another option (though not the best one; pinning mBuild seems like it would work) is to install things from a single YAML file, where you can specify where each package comes from. Doing the same with a sequence of commands gets out of hand pretty quickly

See, for example, https://github.com/MolSSI/QCEngine/blob/4b5843b059e9e619a29398cb9c06ed84185ca1c3/devtools/conda-envs/openmm.yaml#L6-L10

**Comment by umesh-timalsina** [comment]
Managing conda envs from yaml files seems to be a good way to go. The issue I have with the current requirements files we have is the following:  We have some dependencies that are not pip installable (`openmm`) so, `pip install -r requirements-test.txt` might fail or grab a package with different version. So, if @mosdef-hub/mosdef-maintainers agree, I would be happy to add an environment file for gmso like we have for foyer at 

https://github.com/mosdef-hub/foyer/blob/35a73b4e8a9106d353ce5ae2d6ad3f612ac51924/docs/docs-env.yml#L1-L18

**Comment by daico007** [comment]
I think we should do that.

**Comment by justinGilmer** [comment]
That seems reasonable to me.
