### ISSUE TITLE
Use ele for handling Elements

### ISSUE THREAD

**Issue by umesh-timalsina** [mosdef-hub/gmso#435]
It might be nice to handle `Elements` in GMSO using the [`ele`](https://github.com/rsdefever/ele) package.

**Comment by rsdefever** [comment]
The functionality is basically identical. The only problem I see is that ele doesn't use unyt (to keep things lightweight), so I'm not sure how we can add that information in.

**Comment by jennyfothergill** [comment]
Since ele keeps its units consistent and documented it shouldn't be a problem, and keeping ele lightweight is good. We could do something like when the element setter is used, `particle.mass = element.mass * unyt.amu`.

**Comment by umesh-timalsina** [comment]
At the very least `ele` could help standardize the following snippet(vis-à-vis datasources used in `ele`) https://github.com/mosdef-hub/gmso/blob/595a6f17a163296d4ffed58bb403ff4413f967c2/gmso/core/element.py#L269-L406. This can be a simple copy/port or can add `ele` as a dependency.
