### ISSUE TITLE
Pydantic Documentation Ideas

### ISSUE THREAD

**Issue by umesh-timalsina** [mosdef-hub/gmso#450]
After #431 was merged, I have been trying different ways to maintain documentation of the core classes. We have an auto documentation module that provides automatic documentation for all our classes when used in an interpreter shell or an IDE. 

![image](https://user-images.githubusercontent.com/11476842/94194032-bedd6d80-fe76-11ea-8e85-e4fa08389b74.png)

Current style:
![image](https://user-images.githubusercontent.com/11476842/94195011-16c8a400-fe78-11ea-966c-912950c2295e.png)

Other alternative is a tabular representation of the Model schema as shown below

![image](https://user-images.githubusercontent.com/11476842/94194308-1c71ba00-fe77-11ea-93df-7f7503b44a6b.png)

**Comment by rsdefever** [comment]
Is there anything we can do to get rid of the `Union` notation in the docs and just have it show the possibilities? I find the tabular representation much easier to follow at a quick glance.

**Comment by umesh-timalsina** [comment]
Agreed. I think we can make some changes to our documentation generation to get rid of that. If that tabular form is good then, we can stick to that.
