### ISSUE TITLE
Increase unit support in Lammpswriter

### ISSUE THREAD

**Issue by justinGilmer** [mosdef-hub/gmso#458]
Just for later notice.

>Yes, the `atom_style` defines the information that gets written out to the data file: https://lammps.sandia.gov/doc/atom_style.html.  Currently we only support the `real` style of units in lammps which uses energy units of `kcal`.

_Originally posted by @rmatsum836 in https://github.com/mosdef-hub/gmso/pull/453#discussion_r497797272_

**Comment by daico007** [comment]
Addressed by https://github.com/mosdef-hub/gmso/pull/701
