### ISSUE TITLE
Add an attribute called member_classes for bonded potentials

### ISSUE THREAD

**Issue by umesh-timalsina** [mosdef-hub/gmso#464]
After #442, we can also create bonded potentials based on atom classes, So, it might be worth it to add `member_classes` to the bonded potentials. This will be required for serialization of a `ForceField` for example.

**Comment by umesh-timalsina** [comment]
The tricky part might be when there's a ForceField that has a bond defined between an atomClass  and atomType

**Comment by uppittu11** [comment]
How is this handled in foyer? Is there a `member_classes` attribute?

**Comment by justinGilmer** [comment]
The conclusion currently is that all of these attributes like atomType vs. atomClass

Or bonds being between classes vs types, should all be moved to "class" attributes, if you want the specificity for a singular atomtype, make the atomclass of that type a more specific name

**Comment by umesh-timalsina** [comment]
Closed by https://github.com/mosdef-hub/gmso/issues/464#issuecomment-705720449
