### ISSUE TITLE
Unit systems

### ISSUE THREAD

**Issue by mattwthompson** [mosdef-hub/gmso#5]
There is some interest in having an internal "unit system" concept, similar to how [LAMMPS](https://lammps.sandia.gov/doc/units.html) handles units. Proper handling of units (#4) will make this trivial when writing/reading to different file formats and converting to external structures, but it is reasonable to expect users to query values while tinkering with systems. (For example, in looking at `topology.positions` or some force constant in an angle potential, some people may prefer some units over others.) I almost only see two unit systems (nm/kJ and A/kcal) used, but in the future we may want to entertain other systems. For example, eV units in metal systems or maybe even dimensionless values in LJ systems.

We should start using only nm and kJ and at some point in the future think about being able to switch between them.

**Comment by justinGilmer** [comment]
Also in #315
