### ISSUE TITLE
Parameters allow invalid units

### ISSUE THREAD

**Issue by rsdefever** [mosdef-hub/gmso#510]
This works as expected:
```python
from gmso.core.atom_type import AtomType
t1 = AtomType(
    name="cc",
    mass=12.010*u.g/u.mol,
    expression="4*epsilon*((sigma/r)**12 - (sigma/r)**6)",
    parameters={
        "sigma": 3.4 * u.angstrom,
        "epsilon": 43.277 * u.K * u.kb
    }
)
print(atom_type.parameters["epsilon"].to("kJ/mol"))
```
```
0.3598249782764351 kJ/mol
```

But if I change the units on epsilon so they are no longer units of energy, I can still create the `AtomType`:
```
```python
from gmso.core.atom_type import AtomType
t1 = AtomType(
    name="cc",
    mass=12.010*u.g/u.mol,
    expression="4*epsilon*((sigma/r)**12 - (sigma/r)**6)",
    parameters={
        "sigma": 3.4 * u.angstrom,
        "epsilon": 43.277 * u.K / u.kb  # this line changed
    }
)
print(atom_type.parameters["epsilon"].to("kJ/mol"))
```
```
UnitConversionError: Cannot convert between 'K**2*s**2/(kg*m**2)' (dim '(temperature)**2*(time)**2/((length)**2*(mass))') and 'kJ/mol' (dim '(length)**2*(mass)/(time)**2').
```

Is there a way we can do consistency checks on the parameter units? I suppose that is difficult since it would require knowing the dimensions of the expression output. Although all potentials should be in dimensions of energy, right?

**Comment by umesh-timalsina** [comment]
@rsdefever I suppose this could be used as a validator but should be specified during object construction:

https://github.com/mosdef-hub/gmso/blob/2c642a8ae946b22213cbda43eb6fc2f941502f6e/gmso/utils/misc.py#L30-L49

**Comment by daico007** [comment]
Addressed in https://github.com/mosdef-hub/gmso/pull/657
