### ISSUE TITLE
Error creating dihedral type

### ISSUE THREAD

**Issue by rsdefever** [mosdef-hub/gmso#513]
I'm trying to create a `DihedralType` object and I'm getting an error I don't quite understand:

**Code**:
```python
DihedralType(
    name="Test dihedral",
    expression="kn * (1 + cos(n * a - a0))",
    parameters={
        "kn": float(kn) * u.K * u.kb,
        "n": int(n) * u.dimensionless,
        "a0": float(a0) * u.degree, 
    }
)
```

**Error**:
```
ValueError: symbol phi is not in expression's free symbols. Cannot use an independent variable which doesn't exist in the expression's free symbols {a, kn, n, a0}
```

**Comment by umesh-timalsina** [comment]
@rsdefever. This is related to #509, where you specified the parameters for this `DihderalType` but didn't explictly the independent variable and its got the default value which is `phi`.

**Comment by rsdefever** [comment]
Thanks @umesh-timalsina, I didn't realize I needed to specify the independent variables. Easy enough 👍 .
