### ISSUE TITLE
Definitions of supported functional forms for simulation engines

### ISSUE THREAD

**Issue by summeraz** [mosdef-hub/gmso#52]
Disclaimer: I'm not 100% caught up on all the activity and discussion here and am still not very familiar with `sympy`, so feel free to close if this suggestion doesn't make sense.

It might be useful to keep some sort of library where we have files for each simulation engine that define the various supported functional forms for each interaction type. I'm thinking a file structure that's something like (with better names):
```
supported_functional_forms/
|-- gromacs/
| |-- nonbonded.txt
| |-- bond.txt
| |-- angle.txt
...
```
And then, e.g., `nonbonded.txt` would list the supported nonbonded functional forms:
```
4*epsilon*((sigma/r)**12 - (sigma/r)**6)
...
```

This way, if we have a topology with our various functional forms defined for each interaction, we can have a check that interfaces with the library when attempting to save to a certain format as to whether or not the engine supports the defined functional forms. Even better, we could have a property on the `Topology` that's something like `supported_formats` that could be queried to see which writers are available based on the defined functional forms for that topology.

There would likely be some snags with functional forms that are technically equivalent, but defined in slightly-different ways. This is where my lack of knowledge of `sympy` comes in, as I'm not sure how easy that would be to handle. It looks like a similar discussion is ongoing  in #31 with regard to harmonic potentials with and without the 0.5 scaling.

**Comment by daico007** [comment]
This is currently checked in individual writer (list of supported potential forms).
