### ISSUE TITLE
Loading larger ForceField files is not performant

### ISSUE THREAD

**Issue by umesh-timalsina** [mosdef-hub/gmso#521]
It might be nice to investigate why the creation of a `ForceField` for larger files takes a long time. To my knowledge, this is because of the long time it takes to build and validate potential expressions for the potential groups from the XML file. It might be nice to find and cache the potential expression validation function and/or do some smart creation of potentials while creating a `ForceField`. It might also be nice to consider some other avenues for optimizing reading forcefield XML files.

**Comment by umesh-timalsina** [comment]
Loading in `oplsaa_gmso.xml`:
```py
>>> timeit.timeit("from gmso import ForceField;ForceField('oplsaa_gmso.xml', strict=False)", number=1, globals={'get_path': get_path})
41.384391662984854

```

**Comment by rsdefever** [comment]
Yeah thats not going to fly. Most force fields are going to have the same potential expressions _over and over and over and over and over_. Since GMSO is supposed to be flexible we need to be able to handle the case when the potentials _are_ different. But I agree, some sort of caching or other optimization strategy would be helpful. This is such a simple solution that it is probably dumb, but could we just cache the exact strings used for the potential expression -- and if they are the same then call it a match and go on?

**Comment by umesh-timalsina** [comment]
Yeah. We might need to resort to some delayed validation for the `PotentialExpression`. Basically, your XML file is already validated such that, your expressions and independent should match before you create a `PotentialExpression`. Regardless, the fist step I think here should be:
1. memoizing the `@staticmethods` [here](https://github.com/mosdef-hub/gmso/blob/fee3df261a74e39977a5f5d51ca4abd408aca2db/gmso/utils/expression.py#L211-L307). 
2. A delayed validation of `PotentialExpression` on demand.

**Comment by mikemhenry** [comment]
@umesh-timalsina have you tried to profile the code to figure out where it is spending the most time? There could be some really low-hanging fruit.

**Comment by umesh-timalsina** [comment]
@mikemhenry Yeah. I profiled the creation `opls` forcefield using `vprof`. The code heatmap shows that around 21% of the time is spent on validating expression with their parameters. Which doesn't need to happen for an already validated XML IMO. 
[ffcreate.json.zip](https://github.com/mosdef-hub/gmso/files/6093097/ffcreate.json.zip)
A lot of time is being spent in validation of `MetadataMixin` as well.

**Comment by mikemhenry** [comment]
Cool, then an LRU cache should really speed that up

**Comment by daico007** [comment]
Now handled by `forcefield-utilities`
