### ISSUE TITLE
Add index method to `Atom` that takes a topology as an argument

### ISSUE THREAD

**Issue by rsdefever** [mosdef-hub/gmso#557]
Currently, in order to get the atom index of an atom in a topology I am required do the following:
```python
top.get_index(atom)
```

This gets ugly for something like:
```python
top.get_index(angle.connection_members[0])
```

Would it make sense to add something like?
```python
atom.idx(top)
angle.connection_members[0].idx(top)
```

**Comment by daico007** [comment]
implemented, slightly different syntax (`top.get_index(atom))`
