### ISSUE TITLE
Parmed Impropers 

### ISSUE THREAD

**Issue by umesh-timalsina** [mosdef-hub/gmso#577]
It might be nice to convert parmed impropers into `Improper` and applying correct types. Currently dihedral is converted to a gmso `Dihedral` regardless of it being an `improper` in `parmed`.
https://github.com/mosdef-hub/gmso/blob/69e8d0df21d11b80ff6994fa59f783c4ef5c1f75/gmso/external/convert_parmed.py#L157-L163

**Comment by daico007** [comment]
Addressed in https://github.com/mosdef-hub/gmso/pull/658
