### ISSUE TITLE
Issue with mBuild Conversion

### ISSUE THREAD

**Issue by CalCraven** [mosdef-hub/gmso#581]
# Description of Issue:
Having an issue with the element conversion when converting a `gmso.Topology` to an `mBuild.Compound`. Whenever the elements are set for each `site in gmso.topology.sites()`, mBuild still grabs the `site.name` instead of `site.element`. I believe site.element should be the default to convert to `compound.particle.element`.

# Code to reproduce issue:
```python
>>> import gmso
>>> from gmso.external.convert_mbuild import to_mbuild
>>> from gmso.core.element import element_by_symbol
>>> top = gmso.Topology(name='top1')
>>> atom = gmso.Atom(name='atom1', position=[0.0,0.0,0.0], charge=0.0, 
element=element_by_symbol('C'))
>>> top.add_site(atom)
>>> compound=to_mbuild(top)
>>> for part in compound.particles():
>>>   print(part.element)
>>> for part in topology.sites:
>>>   print(part.element)

Output:
None
name='carbon' symbol='C' atomic_number=6 mass=unyt_quantity(1.9944733e-26, 'kg')
```

# Versions
gmso = '0.6.0'
python = 3.7

**Comment by daico007** [comment]
Good catch, we probably for got to update the gmso conversion when mbuild switch to `ele`
