### ISSUE TITLE
Refactor `identify_connections` to return just indices

### ISSUE THREAD

**Issue by umesh-timalsina** [mosdef-hub/gmso#587]
While typing a gmso topology with foyer, we noticed that there are some connections created based on `identify_connections` function that add connections to a topology where its not needed (i.e. parameters for that specific set of connections don't exist in the forcefield).  As, @bc118, @daico007 and @justinGilmer correctly pointed out in our eariler discussion, it might be nice to only add a connection where the parameters actually exist. This is the default behavior for foyer. In order to make it happen, we can refactor the identify connections function to optionally return atom indices.

**Comment by daico007** [comment]
Implemented in #588
