### ISSUE TITLE
1-4 bonding constants and combining rules may be outputting wrong

### ISSUE THREAD

**Issue by bc118** [mosdef-hub/gmso#617]
- The 1-4 bonding constants (vdw and electro) seem to always output 0.5, when using:
new_structure_iteration.scaling_factors["vdw_14"]
new_structure_iteration.scaling_factors["coul_14"]

- The combining rules seem to be only outputting geometric.  Is this the default, and if so, where is it set in the GMSO XML?

I could also be doing something wrong, so please correct me if I am.

**Comment by daico007** [comment]
For this issue, the 1-4 bonding constants should be fixed by https://github.com/mosdef-hub/foyer/pull/489 and the `combining_rule` issue should be fixed by https://github.com/mosdef-hub/gmso/pull/629
