### ISSUE TITLE
New feature request:  atom to molecule mapping or vice versa

### ISSUE THREAD

**Issue by bc118** [mosdef-hub/gmso#625]
I think it may be nice to have an atom-to-molecule mapping, or a similar feature, callable by a function.  For example, the PDB and PSF writers need to know what atoms are bonded to other atoms to issue a unique atom name per molecule.  Therefore, if we know the atom we know what other molecules it is bonded to.  

This may be simpler to do a molecules-to-atoms mapping.

I suspect I am not the only one who this may be nice for, but maybe I am.

**Comment by bc118** [comment]
I created a molecule to atom mapping in for GOMC-MoSDeF-GMSO, so we can see if it is best to make a separate function out of it.

**Comment by daico007** [comment]
Now doable with the site.molecule and site.residue systems (may need some optimization or redesign in the future though)
