### ISSUE TITLE
Wrong expression in convert to foyer xml

### ISSUE THREAD

**Issue by chrisiacovella** [mosdef-hub/gmso#628]
The SymPy expressions are not consistent with foyer forcefield file.  E.g.,:

            "expression": "epsilon * ((sigma/r)**12 - (sigma/r)**6)",

https://github.com/mosdef-hub/gmso/blob/cc0f42d8cfda9b4236c0f1f4b724dc99036427f3/gmso/external/convert_foyer_xml.py#L249

These needs the factor of 4 out front.  Similarly harmonic potentials need the 1/2:

            "expression": "k * (r-r_eq)**2",

https://github.com/mosdef-hub/gmso/blob/cc0f42d8cfda9b4236c0f1f4b724dc99036427f3/gmso/external/convert_foyer_xml.py#L293

The output from, e.g., the LAMMPS writer is still correct, because it assumes the expression consistent with the original foyer XML file and does not directly examine the SymPy expression.

**Comment by daico007** [comment]
Pretty sure this is the cause for this issue https://github.com/mosdef-hub/gmso/issues/624

**Comment by chrisiacovella** [comment]
I agree, that seems to be the likely cause.
