### ISSUE TITLE
Account for mass in convert_mbuild.py

### ISSUE THREAD

**Issue by chrisjonesBSU** [mosdef-hub/gmso#664]
mBuild's Compound class has a mass attribute, I think it would be useful to account for that when using `from_mbuild` and `to_mbuild` in `convert_mbuild.py`

This would be especially useful when working with coarse-grained, or more abstract sytems, where element information isn't applicable.

**Comment by daico007** [comment]
That sounds like a good idea! I will incorporate that into #638
