### ISSUE TITLE
Use `forcefield-utilities` to load a GMSO xml file

### ISSUE THREAD

**Issue by umesh-timalsina** [mosdef-hub/gmso#670]
After https://github.com/mosdef-hub/forcefield-utilities/pull/5, the [`forcefield-utilities`](https://github.com/mosdef-hub/forcefield-utilities) package will have capabilities to parse gmso XML files. It is more performant that the current XML loading utilities in GMSO.

**Comment by daico007** [comment]
Addressed by https://github.com/mosdef-hub/gmso/pull/749
