### ISSUE TITLE
Unyt Issues

### ISSUE THREAD

**Issue by CalCraven** [mosdef-hub/gmso#677]
Unyt has had recent releases that break for python 3.6 and 3.7 and have dropped their support(https://pypi.org/project/unyt/) in version 2.9. As such we needed to pin to unyt version 2.8.0, but we may need to look at these bugs and consider also dropping python 3.6 and 3.7.

**Comment by umesh-timalsina** [comment]
Currently, we are sticking to `unyt<2.9.2`

**Comment by CalCraven** [comment]
This if fixed for now, we can discuss dropping 3.6 and 3.7 at a later date in GMSO to handle this change in Unyt.
