### ISSUE TITLE
Performance issue when converting typed topology to parmed 

### ISSUE THREAD

**Issue by daico007** [mosdef-hub/gmso#717]
For large system, conversion going from a typed topology to parmed can be quite slow. A quick profiling determine that this has to do with a check we perform to make ensure that the converted type is supported via parmed. The check uses sympy to parse the expression and is the bottle neck of the conversion. Replacing sympy with symengine may mitigate the issue.

**Comment by chrisjonesBSU** [comment]
@daico007 can we close this since you merged pr #719 ?
