### ISSUE TITLE
Is there a way to remove sites from a topology?

### ISSUE THREAD

**Issue by chrisjonesBSU** [mosdef-hub/gmso#736]
Is there a way to remove/delete a particle from a topology? For example, if someone wanted to delete/remove all hydrogens after applying a forcefield?  Obviously, mBuild supports this, and Parmed does as well with the `.strip` method.  

It's a little tricky, we need hydrogens in place in order for the SMARTS matching to work.

Here is a simplified example of how we would do it when using mbuild, Foyer (via Parmed):

```
system = mb.Compound(...)
typed_system = foyer.Forcefield.apply(system) # Parmed Structure
typed_system.strip(hydrogens) # Remove hydrogens
snapshot, ff = mb.create_hoomd_forcefield(typed_system)
```

I'm curious if there is a way to do a similar process in GMSO as well, and what kind of complications would come up if we tried to add it.

**Comment by daico007** [comment]
Hi Chris, I don't think we have that feature yet. There was an attempt by Umesh a while back but it was based on the old API (https://github.com/mosdef-hub/gmso/pull/370). It's probably time to revive that effort. In the mean time, I think you can try manually remove site from the top level (and all connection objects that the site is a part of), but I don't know how smooth that will be (probably gonna be a trial-error process, fixing error raised by writers, etc). I will start working on that `delete_site` method this week.

**Comment by CalCraven** [comment]
There is not a method currently in place for this, but it wouldn't be too difficult to include. The topology stores everything in protected attributes with the `self._attribute` syntax. We can access and modify the topology by creating a @setter decorator that can modify the self._sites IndexedSet using the set `discard` method. The complexity would come where we would have to iterate over the rest of the topology and remove connections that contain that site as well. Not extremely difficult, we already have an [iter_sites method](https://github.com/mosdef-hub/gmso/blob/e488a038fc33146d300d56c9708bd31ddf612246/gmso/core/topology.py#L1286), so could be useful to put together an iter_connections method that would take as `key="connection_member", value=site_to_remove`.

**Comment by chrisjonesBSU** [comment]
Ok, thanks for the help!  I'll try and take a look at this as well.
