### ISSUE TITLE
Breaking changes in gsd 3.0

### ISSUE THREAD

**Issue by chrisjonesBSU** [mosdef-hub/gmso#738]
GSD 3.0 was recently released, and how some breaking changes in its API.  It moves away from the `Snapshot` terminology and instead uses `Frame`

Example:

```
>>> import gsd.hoomd
>>> snap = gsd.hoomd.Snapshot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'gsd.hoomd' has no attribute 'Snapshot'
>>> frame = gsd.hoomd.Frame
>>>
```

This causes some issues in `convert_hoomd`.  I changed the version pinning for GSD in #737 as the tests were failing, but we'll still have to make some changes to support both gsd 2 and gsd 3.

**Comment by chrisjonesBSU** [comment]
I have a PR ready to go that adds some checks to `io.py` and `convert_hoomd` that supports both gsd 2.0 and 3.0.  

I'm curious though what others think is the best way to proceed.  `gsd.hoomd.Frame` is introduced in `gsd 2.8` So, we could update `convert_hoomd` to use `Frame` and still technically support both major versions with `gsd >= 2.8`

**Comment by daico007** [comment]
If they (`gsd.hoomd.Frame` and `gsd.hoomd.Snapshot`) is doing the same thing, my vote is to update all the syntax to work with `gsd.hoomd.Frame` and pin gsd to be >2.8

**Comment by CalCraven** [comment]
I would second the adoption of gsd.hoomd.Frame, and pinning to >2.8.
