### ISSUE TITLE
Numpy 1.25.0 will no longer support comparison to string

### ISSUE THREAD

**Issue by CalCraven** [mosdef-hub/gmso#740]
Coming up on unintended behavior when we try to compare attributes of a parametric potential to a null string with determining what to write for XML handling.

The line in question only works for numpy<=1.24.3. Probably can fix this single line so unyt arrays are not compared to this null string, and we can avoid that becoming an issue.
https://github.com/mosdef-hub/gmso/blob/e488a038fc33146d300d56c9708bd31ddf612246/gmso/core/parametric_potential.py#L220

**Comment by CalCraven** [comment]
Issue is being discussed in unyt via:
https://github.com/yt-project/unyt/issues/431

**Comment by daico007** [comment]
Resolved after #764
