### ISSUE TITLE
Multiple Dihedral types (equations)  not accepted (Example: CHARMM style with Periodic and Harmonic dihedrals)

### ISSUE THREAD

**Issue by bc118** [mosdef-hub/gmso#777]
Multiple Dihedral types (equations) not accepted (Example: CHARMM style with Periodic and Harmonic dihedrals)

**_Multiple dihedral types should be accepted for both the proper and improper dihedrals_**.  This is the standard input in the CHARMM format.  However, in CHARMM, the harmonic dihedrals (proper and improper) are listed as periodic with n=0 (yes, this can be confusing.

We should allow different dihedral types, entering correctly the periodic and harmonic forms as the equations define (see the attached XML).  In MoSDeF-GOMC, we will read the proper and improper harmonic dihedrals and write them as the proper and improper periodic dihedrals with n=0 for the CHARMM FF style (required for CHARMM style format - yes, it is confusing). Each writer should handle this separately for their suited engines, where this specific formatted example is for NAMD and the future GOMC once harmonic dihedrals are added.

This is critical if we ever want to be able to use the CHARMM FF in MoSDeF force fields/simulations. 

I have provided an example of a proper periodic and harmonic dihedral that fails due to the different dihedral styles.  

[gmso_ff_with_periodic_and_harmonic_dihedrals.zip](https://github.com/mosdef-hub/gmso/files/13060643/gmso_ff_with_periodic_and_harmonic_dihedrals.zip)

**Comment by CalCraven** [comment]
We have an open PR for this that has gone stale. Would you consider trying to restart this? I think you would just "layer" dihedrals to make the full harmonic and periodic pseudo-hybrid PR that CHARMM likes to use.
https://github.com/mosdef-hub/gmso/pull/569

**Comment by bc118** [comment]
Yeah,  I believe this issue does overlap with the PR you mentioned above.  Maybe we add these comments to that PR?

**Comment by bc118** [comment]
I moved my comments in to PR https://github.com/mosdef-hub/gmso/pull/569, so I closed this one.
