### ISSUE TITLE
GOMC support

### ISSUE THREAD

**Issue by ahy3nz** [mosdef-hub/gmso#78]
Needs:

- Be able to read `.par` files (Parmed does this, but doesn't support some of the functionals that GOMC/NAMD need to use)
- `.par` files limit atomtypes to only 4 characters, so this could potentially cause issues for writer
- On the bright side, I think Parmed can read `.par` files, create the `ParameterSet`, and then output the OMM FFXML
- GOMC workflows have to involve manually specifying atomtypes in their topology files. They use a lot of CHARMM atomtypes, so I think there would be a need to add SMARTS definitions for the atomtypes, or just use the hackyCG method that I use for specifying charmm atomtypes
- Current GOMC work flows do take 'prototype' molecules and call packmol already, but use VMD to specify parameters
- The need to accommodate Mie nonbonded potentials, and making sure we can read this in a FFXML. We might not need to parse the tag like "HarmonicBondForce" or "CustomBondForce", but rather just needing to parse the energy expression via `sympy`

For reference:
[GOMC documentation](https://gomc-wsu.github.io/Manual/software_tools.html)

**Comment by daico007** [comment]
Now handled by https://github.com/GOMC-WSU/MoSDeF-GOMC
