### ISSUE TITLE
Methods to check validity against supported engines

### ISSUE THREAD

**Issue by mattwthompson** [mosdef-hub/gmso#80]
At a simple level, we could have a function `top.compatable_engines()`/`top.compatable_formats()` that calls various writers' validation functions to see if a topology could be written to an engine. Maybe at different levels of yes/no/maybe

A build-off of this could be some user warnings while changing things, for example if an `AtomType.nb_function` is changed from something that everything supports (i.e. Lennard-Jones) to something that some support (i.e. Mie) to something that nobody supports (a typo potential).

**Comment by daico007** [comment]
should have been addressed by `compatibility.py`
