### ISSUE TITLE
Topology properties and update functions

### ISSUE THREAD

**Issue by ahy3nz** [mosdef-hub/gmso#84]
From anecdotal experience with Parmed, it becomes helpful to access the unique bond/angle/dihedral/atom types - this is often a first step in a lot of writers. There should be properties like `top.unique_bond_types`, `top.unique_atom_types`. Going further, there could be functionality like `top.unique_bond_functionals` (which would call `top.unique_bond_types` and parse the functional). 

Noting that things like `top.unique_bond_types` are a property/attribute, we would need `top.update_topology()` to re-parse the unique_bond_types, unique_atom_types, etc. In implementation, `top.update_topology()` would probably call smaller update functions like `top.update_bonds()`, `top.update_angles()`. These smaller update functions would be useful/faster for modifying a single bond - we don't need to `top.update_topology()`, we'd really only need `top.update_bonds()`

I'll flesh out the code, but this will probably depend on some other PRs that are pretty much ready to be merged. Furthermore, these properties/update functions will need to be expanded in parallel with the "scope" of pyTopology's acceptable force field terms (+1 for pyTopology name)

**Comment by daico007** [comment]
These properties are now generated on the flight
