### ISSUE TITLE
Add option to write atom types/names in xyz writer instead of element?

### ISSUE THREAD

**Issue by chrisjonesBSU** [mosdef-hub/gmso#847]
In [mBuild's xyz writer](https://github.com/mosdef-hub/mbuild/blob/c79a58e54f16b76bb540553dd2930da0e758951e/mbuild/formats/xyz.py#L96) we had a flag that if `True` wrote out the atom names (i.e. types) instead of the elements. In GMSO's xyz writer we just write out the elements. As we are removing most of mBuild's writers and using GMSO in the backend, is this something we want to bring over to GMSO?

**Comment by CalCraven** [comment]
I don't think that's a useful feature. XYZ files don't contain typing information anyways, so it would never need to be written here. It's mostly just an indexed list of coordinates. As far as I'm aware, no engines would need the atomtype information from this file.

**Comment by chrisjonesBSU** [comment]
Ok, yeah that sounds good to me as well!
