### ISSUE TITLE
Proper connection syntax 

### ISSUE THREAD

**Issue by ahy3nz** [mosdef-hub/gmso#86]
Right now, there are sort of multiple ways to add connections in a topology, one of which might not function intuitively:
* Create a `Connection` object, and this will call `site1.add_connection` & `site2.add_connection`. This makes no relation to the `Topology`. You would have to call `Topology.add_connection(Connection)`. If done this way, you can give a  `ConnectionType` to `Connection`
* Create a `Connection` object, and this will call `site1.add_connection` & `site2.add_connection`. This makes no relation to `Topology`. If a user calls `Topology.update_connection_list`, we iterate through a site and its connections. Using this iteration, there is no information about the `ConnectionType` when we modify `Topology.connection_list`
* I can imagine it'll be important to update connections for non-parametrized systems, but the when + where to use these calls seems a little confusing. 

Specifically, for a _parametrized_ system, we have to explicitly create the `Connection` object and call `top.add_connection` (otherwise `ConnectionType` is lost) 

For a _non-parametrized_ system, we don't need to call `top.add_connection`. We can settle with `top.update_connection_list()` (which will ignore `ConnectionType` info)

Further, there could be "clobbering" issues. `top.update_connection_list` will check for an existing connection in `top.connection_list`, but `top.add_connection` makes no such check

**Comment by daico007** [comment]
connections can now only be added from the topology level
