### ISSUE TITLE
Should we hash topologies (and their components)?

### ISSUE THREAD

**Issue by mattwthompson** [mosdef-hub/gmso#90]
Related to #17 #14, should we define a hash for a topology, and also its components? It would be needed to make dictionaries with keys being individual sites like we've done in the mbuild converter (see [this](https://github.com/mattwthompson/topology/pull/14#issuecomment-469952842)).

Right now we think we should do this for the high-level `Topology` and probably do it for other components (`Site`, `Box`, etc.). A good starting point would just be setting the id to the hash (like [this](https://stackoverflow.com/a/1608888/4248961) guy or gal did).

@justinGilmer what say you?

**Comment by daico007** [comment]
Should now be handled via pydantic serialization
